name: 11_ステータスチェック関数・ワークフローのスキップ.yaml
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # 普通だったらこの時点で即終了
      - run: exit 1
      # でもステータスチェック関数があるおかげで下の行も実行される。
      # 必ずifキーとセットで使用しないといけない。
      # よくある使い方としては、失敗時にも通知するみたいな感じ。 
      - run: echo "Hello"
        if: ${{failure()}}
  skip:
    runs-on: ubuntu-latest
    # jobの段階でスキップもできる。これやると、時間が加算されないから一番コスト削減できる。
    if: ${{github.actor != 'azarasi1226'}}
    steps:
      - run: echo "マジすか？"
