name: 23_Environments
on:
  workflow_dispatch:
    # 手動実行する際のパラメーター
    inputs:
      greeting:
        # 型
        type: string
        # デフォルト値 (入力されてる値を消して実行してもこの値が入っていた)
        default: Hello
        # 必須フラグ (デフォルト指定して、これ指定する意味あるんか？)
        required: true
        # 説明
        description: A cheerful word
jobs:
  run:
    runs-on: ubuntu-latest
    # 環境の切り替えはここで行う
    environment: ${{inputs.environment}}
    env:
      USERNAME: ${{vars.USERNAME}}
      PASSWORD: ${{secrets.PASSWORD}}
    steps:
      - run: echo "userName- ${USERNAME}"
      - run: echo "password- ${PASSWORD}"