name: 23_Environments
on:
  push:
  workflow_dispatch:
    inputs:
      environment-name:
        # typeがenvironmentだと、存在する環境セットしか出てこなくなる。
        type: environment
        description: '対象環境'
        required: true
        default: 'test'
jobs:
  run:
    runs-on: ubuntu-latest
    # 環境の切り替えはここで行う
    environment: ${{inputs.environment-name}}
    env:
      USERNAME: ${{vars.USERNAME}}
      PASSWORD: ${{secrets.PASSWORD}}
    steps:
      - run: echo "userName- ${USERNAME}"
      - run: echo "password- ${PASSWORD}"