name: 24_アーティファクト
on: push
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: ファイル作成
        run: date > date.txt
      - name: アーティファクトのアップロード
        uses: actions/upload-artifact@v4
        with:
          name: date-file
          path: ./date.txt
          retention-days: 7
  download:
    runs-on: ubuntu-latest
    needs: [upload]
    steps:
      - name: アーティファクトのダウンロード
        uses: actions/download-artifact@v4
        with:
          name: date-file
          path: ./downloaded
      - name: ファイル内容の表示
        run: cat date.txt