name: Manual
# ONの下にworkflow_dispatchを指定すると手動実行
on:
  workflow_dispatch:
    # 手動実行する際のパラメーター
    inputs:
      greeting:
        # 型
        type: string
        # デフォルト値
        default: Hello
        # 必須フラグ (デフォルト指定して、これ指定する意味あるんか？)
        requiredc: true
        # 説明
        description: A cheerful word
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{inputs.greeting}}"
