name: Context Reference
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Repository: ${{ github.repository }}"
      - run: echo "Event Name: ${{ github.event_name }}"
      - run: echo "SHA: ${{ github.sha }}"
      - run: echo "Ref: ${{ github.ref }}"
      - run: echo "Actor: ${{ github.actor }}"