name: 5_yaml内定義の環境変数2
on: push
env:
  EXAMPLE: 初期値だよ
jobs:
  run:
    runs-on: ubuntu-latest
    # オーバーライドは、スコープが狭いところが優先される
    env:
      EXAMPLE: ジョブレベルで上書きしたよ
    steps:
      - run: echo ${EXAMPLE}
      - run: echo ${EXAMPLE}
       # ステップレベルの環境変数の書き方,なんか定義と処理が上下してキモイな
        env: 
          EXAMPLE: ステップレベルでさらに上書きしたよ
      - run: echo ${EXAMPLE}