name: 7_repositoryレベルの環境変数
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      # 中間環境変数にして安全にする
      REPO_LEVEL_ENV: ${{vars.REPOSITORYENV}}
      REPO_LEVEL_ENV2: ${{vars.NOT_EXISTING_ENV_VAR}}
    steps:
      - run: echo "${REPO_LEVEL_ENV}"
      - run: echo "${REPO_LEVEL_ENV2}"