name: 7_repositoryレベルの環境変数・Secret
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      # Variablesの参照方法確認用
      REPO_LEVEL_ENV: ${{vars.REPOSITORYENV}}
      # Secretの参照方法確認用
      PASSWORD: ${{secrets.PASSWORD}}
      
    steps:
      - run: echo "${REPO_LEVEL_ENV}"
      - run: echo "${PASSWORD}"
      # シークレットに登録された文字列はそのままだとマスクされるポイ。
      - run: echo "mazisuka?"