name: repositoryレベルの環境変数
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      # 中間環境変数にして安全にする
      REPO_LEVEL_ENV: ${{vars.REPOSITORYENV}}
    steps:
      - run: echo "${REPO_LEVEL_ENV}"